Feature/cypress
vtex-apps/fedex-shipping pull request #39
Opened 2022-07-28 10:34 UTC by saravananvenkatesan

2022-07-28 11:27 UTC, Syed-Vtex requested changes
@saravananvenkatesan Can you please have a look

2022-07-28 11:27 UTC, Syed-Vtex commented on cy-runner.yml
> +      enabled: false
deployCli always should be true 
in your local, you can have false but you should not push

2022-07-28 11:27 UTC, Syed-Vtex commented on cy-runner.yml
> +    board: AVAILABLE
change board name to fedex shipping jira board name

2022-07-28 11:27 UTC, Syed-Vtex commented on cy-runner.yml
> +    projectId: 32v7vx
https://dashboard.cypress.io/projects/72oi9b/runs

Replace 32v7vx with 72oi9b

2022-07-28 11:27 UTC, Syed-Vtex commented on cy-runner.yml
> +    # location-availability theme will work only when its peer dependency location-availability is added in the workspace
Update this hardcoded text
Please pay attention before push

2022-07-28 11:27 UTC, Syed-Vtex commented on cypress/support/fedex.outputvalidation.js
> +  data: {
Move this fixtures
It should not be here

2022-07-28 11:27 UTC, Syed-Vtex commented on cypress/support/fedex.outputvalidation.js
> +  data: {
Here, I'm mentioning the payload which we send for shipping rates
Move to shippingRatePayload.json

2022-07-28 11:27 UTC, Syed-Vtex commented on cypress/support/fedex.graphql.js
> +  const APP_NAME = 'vtex.wish-list'
Please check before push
Here why it is been mentioned as vtex.wish

2022-07-28 11:27 UTC, Syed-Vtex commented on cypress/support/fedex.apis.js
> +    cy.addDelayBetweenRetries(2000)
We add cy.addDelayBetweenRetries only when api is taking longer time
If it is not taking longer time then we should not use

2022-07-28 11:27 UTC, Syed-Vtex commented on cypress/support/apis.endpoint.js
> +export default {
File name should only use _
eg: apis_endpoint.js
+
If code is avaiable in fedex repo then it is clear that code is been used by fedex testcases
So, you don't need to mention fedex.apis.js ->>>>> apis.js is fine ->>>> Change this everywhere

2022-07-28 11:29 UTC, Syed-Vtex commented on cypress.json
> +{}
@shashidhar85 Remove cypress.json

2022-07-28 11:29 UTC, Syed-Vtex commented on cy-runner.yml
> +      - cypress-shared/integration/shopper-location/2.4-enable-Location-via-browser-popup-order-product.spec.js
@shashidhar85 Fix cy-runner.yml

2022-07-28 11:55 UTC, Syed-Vtex requested changes

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +import { loginViaAPI } from '../../cy-runner/cypress-shared/support/common/support.js'
It is referring to cy-runner ... 
It should use from support common folder
We used loginViaAPI to solve location availability app because there if we use testSetup then location popup was not working.

So, please use testSetup here

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +import { preserveCookie, updateRetry } from '../support/common/support.js'
import testSetup

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +const prefix = 'Single Product'
Let's move prefix to outputvalidation
So,

const { productName, prefix } = singleProduct

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +        cy.log(text.split(' '))
Remove log

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +    cy.get(fedexSelectors.ShippingSelectContainer).select('FedEx Home Delivery')
Store all SLAs in sla.json or sla.js file and let's try to access from there
So, that we don't want to harcode on multiple places

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +        cy.get(fedexSelectors.CurrentShippingSLA).contains('1 business day')
Move to sla.js or sla.json file

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product-scenarios.spec.js
> +  preserveCookie()
Here we don't have anonymous user right.
So, just try to preserve cookies using regex

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.2-multi-product-scenarios.spec.js
> +  loginViaAPI()
Same goes here, 
use testSetup()

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.2-multi-product-scenarios.spec.js
> +    cy.wait(10000)
Keep an eye on this
Try to change it to intercept
This you can do later as we proceed

Because, in Github Actions there is no guarantee that 10s is underwait or overwait

2022-07-28 11:55 UTC, Syed-Vtex commented on cypress/integration/2.2-multi-product-scenarios.spec.js
> +    cy.searchProduct(productName1)
In index.js 
there is no import that is coming from commands.js
So, i feel this cy. commands will fail

2022-07-28 14:00 UTC, Syed-Vtex commented on cypress/support/apis.endpoint.js
> +export default {
@saravananvenkatesan

2022-08-01 12:40 UTC, Syed-Vtex commented on cypress/integration/2.5-hide-sla-scenarios.spec.js
> +      graphql(
@saravananvenkatesan Fix prettier

2022-08-01 12:40 UTC, Syed-Vtex commented on cypress/support/commands.js
> +    return slaSettings
Fix warning @saravananvenkatesan

2022-08-01 12:48 UTC, Syed-Vtex requested changes

2022-08-01 12:48 UTC, Syed-Vtex commented on cypress/integration/2.5-hide-sla-scenarios.spec.js
> +      cy.getSettings(response.body)
getSettings to
writeAppSettingsInJSON

Also add comment in command.js file like why we are writing response to JSON File

2022-08-01 12:48 UTC, Syed-Vtex commented on cypress/integration/2.5-hide-sla-scenarios.spec.js
> +  // Adding Product to Cart & Verifying shipping method not shows
Remove this comment

2022-08-01 12:48 UTC, Syed-Vtex commented on cypress/integration/2.6-show-sla-scenarios.spec.js
> +  calculateShipping(data)
Add some validation for hide and show sla

2022-08-01 12:48 UTC, Syed-Vtex commented on cypress/integration/2.5-hide-sla-scenarios.spec.js
> +  preserveCookie()
preserveCookie() is not needed here
preserveCookie is needed only when we test anonymous user

When we don't test anoymous user
Then, we preserve both admin and user cookie
eg:
Cypress.Cookies.defaults({
  preserve: /VtexIdclientAutCookie/,
})

2022-08-01 12:48 UTC, Syed-Vtex commented on cypress/integration/2.6-show-sla-scenarios.spec.js
> +  preserveCookie()
Remove preserveCookie() in testcases

2022-08-01 12:48 UTC, Syed-Vtex commented on cypress/support/apis.js
> +        if (response.body.length === 0) {
We should not use like this
Because, say fedex API is down on that case this will get passed 
So, it will try to run singleProduct there it will start failing

Update your function/ Follow the strategy which we use in graphql

2022-08-01 12:50 UTC, Syed-Vtex requested changes

2022-08-01 12:50 UTC, Syed-Vtex commented on cypress/fixtures/shippingRatePayload.json
> +        "id": "880340",
May I know why did you changed this

2022-08-01 12:50 UTC, Syed-Vtex commented on cypress/support/fedex.graphql.js
> +export function graphql(getQuery, validateResponseFn = null) {
You have overided my graphql changes this will start breaking graphql testcases

2022-08-01 12:50 UTC, Syed-Vtex commented on cypress/support/fedex.graphql.js
> +export function saveAppSetting(appDatas, allSla, slaName, hide = false) {
Fix this too many parameters thing
Use object to solve

2022-08-01 12:50 UTC, Syed-Vtex commented on cypress/support/fedex.graphql.js
> +  if (allSla) {
FIx warning! - Expected blank line

2022-08-01 12:55 UTC, Syed-Vtex commented on cypress/fixtures/shippingRatePayload.json
> +        "id": "880340",
Apache2020SkuId: '880330',
  Amacsa2020SkuId: '880350',
  
  You should use only these sku ids
  If you want any other product sku ids then please let me know
  @saravananvenkatesan

2022-08-01 13:26 UTC, Syed-Vtex requested changes

2022-08-01 13:26 UTC, Syed-Vtex commented on cypress/integration/2.5-enable-disable-ship-to-residential-toggle.spec.js
> +  testSetup()
a) 2.5 is already taken

2022-08-01 13:26 UTC, Syed-Vtex commented on cypress/integration/2.5-enable-disable-ship-to-residential-toggle.spec.js
> +    cy.hideSla(false).then((sla) => {
@shashidhar85 Can you please create a command 
readAppSettingsFromJSON that will read the file created by getSettings
Also, add some comments over there like why we are doing readAppSettings and writeAppSettings

2022-08-01 13:26 UTC, Syed-Vtex commented on cypress/integration/2.5-enable-disable-ship-to-residential-toggle.spec.js
> +    cy.hideSla(false).then((sla) => {
Don't use hideSla it misleads the reader

2022-08-01 13:26 UTC, Syed-Vtex commented on cypress/integration/2.5-enable-disable-ship-to-residential-toggle.spec.js
> +    cy.getVtexItems().then((vtex) => {
This api is became a common one now
Can you please do this similar to graphql api 
where we can validate if we don't want to do validation then we get back the response

Similarly here also we should return response and validate.

So that, we can avoid repeating below statement
Add review comment
Cancel
      cy.request({
        method: 'POST',
        url: calculateShippingAPI(vtex.account, Cypress.env('workspace').name),
        headers: { VtexIdclientAutCookie: vtex.userAuthCookieValue },
        ...FAIL_ON_STATUS_CODE,
        body: data,
      }).then((response) => {

2022-08-01 13:26 UTC, Syed-Vtex commented on cypress/integration/2.5-enable-disable-ship-to-residential-toggle.spec.js
> +  preserveCookie()
This is not required
Please see above comments on preserveCookie

2022-08-02 12:17 UTC, Syed-Vtex commented on cypress/integration/2.9 -Validate Shipping from different origins.spec.js
> +          expect(filtershippingMethod)
blank line warning

2022-08-02 12:17 UTC, Syed-Vtex commented on cypress/integration/2.9 -Validate Shipping from different origins.spec.js
> +          expect(filtershippingMethod)
blank line warning

2022-08-02 12:17 UTC, Syed-Vtex commented on cypress/integration/2.9 -Validate Shipping from different origins.spec.js
> +      data.destination.zipCode = '33301'
Here you didn't updated the origin to use Italy

2022-08-04 11:59 UTC, Syed-Vtex requested changes

2022-08-04 12:00 UTC, Syed-Vtex commented on cypress/integration/2.11-validate-surcharge-flat-rate.spec.js
> +  testSetup()
@shashidhar85 
loginViaCookies is published now
Take a pull from cy-runner main branch
Now, you can replace testSetup with loginViaCookie

2022-08-04 12:01 UTC, Syed-Vtex commented on cypress/integration/2.11-validate-surcharge-flat-rate.spec.js
> +  testSetup()
Please change in all places

2022-08-05 06:05 UTC, Syed-Vtex commented on cy-runner.yml
> +    enabled: true
@shashidhar85 Disable jira
Set enabled: false

Once everything looks good in Github Actions then we will make this to true

2022-08-05 06:08 UTC, Syed-Vtex commented on cypress/integration/2.10-surcharge-flat-rate-and-surcharge-percentage.spec.js
> +        (b) => b.shippingMethod === 'FedEx Home Delivery'
@shashidhar85 
Please replace hardcoded text and refer from sla.js

2022-08-08 06:55 UTC, Syed-Vtex requested changes

2022-08-08 11:21 UTC, shashidhar85 commented on cypress/support/api_testcase.js
> +        if (response.body.length === 0) {
loadCalculateShippingAPI function is there already in same file

2022-08-09 07:38 UTC, Syed-Vtex commented on cy-runner.yml
> +    enabled: false
@Syed-Vtex 
Before approving this PR
Ensure JIRA is enabled

2022-08-09 07:40 UTC, Syed-Vtex commented on cypress/support/products.js
> +export const PRODUCTS = {
@shashidhar85 Are we using this file

2022-08-09 07:41 UTC, Syed-Vtex commented on cypress/support/commands.js
> +Cypress.Commands.add('getSettings', (data) => {
@shashidhar85 Change this command name to 
getSettings to writeAppSettingstoJSON

2022-08-09 08:57 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +import { PRODUCTS } from './products'
@shashidhar85 
Lint error

2022-08-09 10:06 UTC, shashidhar85 submitted a review, later dismissed

2022-08-09 10:16 UTC, Syed-Vtex commented
@thyarles Can you please help
SonarCloud is failing

2022-08-10 11:26 UTC, Syed-Vtex submitted a review, later dismissed

2022-08-11 06:42 UTC, merged