[FEDEXSHIP-41] App Review
vtex-apps/fedex-shipping pull request #44
Opened 2022-08-09 18:01 UTC by Arturo777

- (FEDEXSHIP-41) Logging optimization
- (FEDEXSHIP-41) GraphQL mutation security
- (FEDEXSHIP-41) Admin navigation permissions

[Workspace to test](https://fedexlogger--sandboxusdev.myvtex.com/)

2022-09-08 17:37 UTC, polishq requested changes

2022-09-08 17:37 UTC, polishq commented on CHANGELOG.md
> +## [1.18.3] - 2022-09-06
Remove duplicate entry

2022-09-08 17:37 UTC, polishq commented on dotnet/Controlers/RoutesController.cs
> +            if (!getRatesResponseWrapper.IsValidCountry) {
```suggestion
            if (!getRatesResponseWrapper.IsValidCountry)
            {
```

2022-09-08 17:37 UTC, polishq commented on dotnet/Controlers/RoutesController.cs
> +                Response.StatusCode = 404;
Add a return to stop the following code from being processed

2022-09-08 17:37 UTC, polishq commented on dotnet/Services/FedExAvailabilityRequest.cs
> +                //ValidationAvailabilityAndCommitmentService service = new ValidationAvailabilityAndCommitmentService(); // Initialize the service
Remove commented code

2022-09-08 17:37 UTC, polishq commented on dotnet/Services/FedExRateRequest.cs
> +                                    // if (!string.Equals(this._environmentVariableProvider.Workspace, "master")) {
Remove commented code

2022-09-08 17:37 UTC, polishq commented on dotnet/Services/FedExRateRequest.cs
> +                                Console.WriteLine($"Exception: {e.Message}");
Log to Splunk?

2022-09-08 17:37 UTC, polishq commented on dotnet/Services/FedExRateRequest.cs
> +                                    foreach(RateReplyDetail detail in reply.RateReplyDetails)
Check for `null` `reply.RateReplyDetails` before performing `foreach`

2022-09-08 17:37 UTC, polishq commented on dotnet/Services/FedExRateRequest.cs
> +                                            TimeSpan transitArrival = detail.DeliveryTimestamp - getRatesRequest.shippingDateUTC;
This causes an error later if there is no `DeliveryTimestamp` in the response. You can check for a `detail.DeliveryTimestampSpecified` boolean in the response; if it's false, skip the SLA

2022-09-09 18:17 UTC, polishq requested changes

2022-09-09 18:17 UTC, polishq commented on dotnet/Services/FedExRateRequest.cs
> +                                RateReply reply = ratesResponse.RateReply;
Let's log this `reply` please

2022-09-09 18:48 UTC, Arturo777 commented on CHANGELOG.md
> +## [1.18.3] - 2022-09-06
done

2022-09-09 18:55 UTC, Arturo777 commented on dotnet/Services/FedExRateRequest.cs
> +                                    // if (!string.Equals(this._environmentVariableProvider.Workspace, "master")) {
done

2022-09-09 19:01 UTC, Arturo777 commented on dotnet/Services/FedExRateRequest.cs
> +                                Console.WriteLine($"Exception: {e.Message}");
done

2022-09-09 19:23 UTC, Arturo777 commented on dotnet/Services/FedExRateRequest.cs
> +                                            TimeSpan transitArrival = detail.DeliveryTimestamp - getRatesRequest.shippingDateUTC;
done

2022-09-09 19:40 UTC, btalma submitted a review, later dismissed

2022-09-15 17:19 UTC, polishq approved these changes
LGTM

2022-09-15 17:47 UTC, polishq requested changes

2022-09-15 17:47 UTC, polishq commented on dotnet/Controlers/RoutesController.cs
> +            if (!getRatesResponseWrapper.IsValidCountry)
Ah, this is why the Cypress test is failing. You're checking for `IsValidCountry` before any API requests have been made. This needs to happen after `getRatesResponseWrapper = await this._fedExRateRequest.GetRates(getRatesRequest);`

2022-09-15 21:14 UTC, Arturo777 commented on dotnet/Controlers/RoutesController.cs
> +            if (!getRatesResponseWrapper.IsValidCountry)
ohhh, ok, i updated the PR!

2022-09-16 13:07 UTC, polishq approved these changes
LGTM

2022-09-16 13:48 UTC, merged