[FEDEXSHIP-42] Added more postal code regex validations
vtex-apps/fedex-shipping pull request #46
Opened 2022-08-16 19:36 UTC by Arturo777

Added more postal code regex validations

2022-08-30 19:59 UTC, polishq requested changes
@Arturo777 Don't forget this other change we discussed on Slack: https://vtex.slack.com/archives/CFJU5HYTV/p1661180823238569?thread_ts=1659547170.177039&cid=CFJU5HYTV

2022-08-31 20:27 UTC, polishq approved these changes
LGTM, just need Cypress to pass

2022-08-31 20:29 UTC, btalma commented on dotnet/Data/Constants.cs
> +            {"ARE", ""},
Did you intend to match an empty pattern?

2022-08-31 20:29 UTC, btalma commented on dotnet/Data/Constants.cs
> +            {"IRL", ""},
Empty pattern?

2022-08-31 20:29 UTC, btalma commented on dotnet/Data/MerchantSettingsRepository.cs
> +            if (merchantSettings.SlaSettings.Count != 21)
This will overwrite all current settings - is that okay?

2022-08-31 20:46 UTC, polishq requested changes

2022-08-31 20:46 UTC, polishq commented on dotnet/Data/MerchantSettingsRepository.cs
> +            if (merchantSettings.SlaSettings.Count != 21)
Maybe we have one condition if the count is 19 where we simply add the two new ones, and another condition if the count is less than 19 where we add all 21 of them?

2022-08-31 20:55 UTC, polishq commented on dotnet/Data/Constants.cs
> +            {"ARE", ""},
United Arab Emirates (ARE) apparently does not use postal codes. An empty pattern matches everything, so this "works" 🤷

2022-08-31 20:55 UTC, polishq commented on dotnet/Data/Constants.cs
> +            {"ARE", ""},
Suggestions welcome, though

2022-09-06 13:59 UTC, btalma approved these changes

2022-09-06 19:19 UTC, merged